stages:
  data_ingestion: 
    cmd: python src\lung_cancer_classifier\training_stages\stage_01_data_ingestion.py
    deps:
      - src\lung_cancer_classifier\training_stages\stage_01_data_ingestion.py
      - config\config.yaml
    outs:
      - artifacts\data_ingestion\Chest-CT-Scan-data


  prepare_base_model:
    cmd: python src\lung_cancer_classifier\training_stages\stage_02_prepare_base_model.py
    deps:
      - src\lung_cancer_classifier\training_stages\stage_02_prepare_base_model.py
      - config\config.yaml
      - params.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts\prepare_base_model


  training:
    cmd: python src\lung_cancer_classifier\training_stages\stage_03_model_trainer.py
    deps:
      - src\lung_cancer_classifier\training_stages\stage_03_model_trainer.py
      - config\config.yaml
      - artifacts\data_ingestion\Chest-CT-Scan-data
      - artifacts\prepare_base_model
      - params.yaml
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts\training\trained_model.h5


  evaluation:
    cmd: python src\lung_cancer_classifier\training_stages\stage_04_model_evaluation.py
    deps:
      - src\lung_cancer_classifier\training_stages\stage_04_model_evaluation.py
      - config\config.yaml
      - artifacts\data_ingestion\Chest-CT-Scan-data
      - artifacts\training\trained_model.h5
      - params.yaml
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false